### ISSUE TITLE
move docs to testing-library.com?

### ISSUE THREAD

**Issue by kentcdodds** [dfcook/vue-testing-library#14]
Hey @dfcook! Would you be interested in moving your docs to https://testing-library.com/vue? (Similar to https://testing-library.com/react and https://testing-library.com/cypress)

The site source is here: https://github.com/alexkrolick/testing-library-docs

I think it'd be pretty trivial to move things over.

What do you think? cc @alexkrolick

**Comment by alexkrolick** [comment]
Yep -it could resemble the pages for react or the shorter one-pagers for Cypress and the jest-dom/user-event ecosystem

**Comment by dfcook** [comment]
Working on it

**Comment by kentcdodds** [comment]
Awesome! Thanks @dfcook!

**Comment by dfcook** [comment]
PR raised for adding the vue section:

https://github.com/alexkrolick/testing-library-docs/pull/14
