### ISSUE TITLE
Feature parity with react-testing-library

### ISSUE THREAD

**Issue by ankitsinghaniyaz** [dfcook/vue-testing-library#4]
I last used `react-testing-library` and just loved it so I'm trying use `vue-testing-library` now. I see that there are some features that are missing or not explained.

1. Not all `dom-testing-libarary` methods are exposed to the user like done for the react library [here](https://github.com/kentcdodds/react-testing-library/blob/master/src/index.js#L87).
2. Ability to [create a custom render](https://github.com/kentcdodds/react-testing-library#custom-render). 

I'm interested in this project and willing to help. Is this something we have on the roadmap?

**Comment by dfcook** [comment]
Hi, I've just pushed an update that will address 1 and also updated to latest versions of the packages, I'm not sure whether 2 can be done within the context of vue-test-utils. If you want to take a look I'm more than happy to accept pull requests.
