### ISSUE TITLE
Why use Simulate.click instead of fireEvent.click?

### ISSUE THREAD

**Issue by ankitsinghaniyaz** [dfcook/vue-testing-library#5]
I was wondering why are we using `Simulate.click` instead of using `fireEvent.click`?

**Comment by dfcook** [comment]
Good spot, I was never happy with Simulate, updated in latest commit.

As an aside, should investigate whether we can roll the call to wait into a wrapper around fireEvent to provide a more convenient handling of vue-test-utils asynchronous updates
