### ISSUE TITLE
Pull request #8 is not published

### ISSUE THREAD

**Issue by ronaldborman** [dfcook/vue-testing-library#9]
When I install the latest version of vue-testing-library, it does not contain pull request #8 .

Strangely enough, the version is 0.10 although the repository says it's 0.9.

Also the Travis build is failing, stating that it cannot find @babel/runtime/helpers/interopRequireDefault when executing the tests.  If I remember correctly, this has something to do with the fact that the Babel helper functions were moved in version 7-beta.56. But I don't know if this is actually the source of this issue.

**Comment by dfcook** [comment]
Sorry for that, just pushed 0.10.1 and fixed the failing Travis build
